### ISSUE TITLE
Problemas con WebSockets

### ISSUE THREAD

**Issue by SergioBenitez755787** [SergioBenitez755787/urlshortener#1]
Invocar el método create desde un ServerEndpoint
https://github.com/SergioBenitez755787/urlshortener/blob/benny/delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/CsvWebSockets.kt

**Comment by fjlopez** [comment]
Let's analyse the code and highlight the issues:

```kotlin
    fun shortener(originalUrl: String, request: HttpServletRequest): String { // we don't have a HTTP request here
        createShortUrlUseCase.create(
            url = originalUrl,
            data = ShortUrlProperties(
                ip = "remoteAddr", // how we can discover the remote IP of the client?
                sponsor = null
            )
        ).let {
            val h = HttpHeaders()
            val url = linkTo<UrlShortenerControllerImpl> { redirectTo(it.hash, request) }.toUri() // will not work here
            h.location = url
            val response = ShortUrlDataOut(
                url = url,
                properties = mapOf(
                    "safe" to it.properties.safe
                )
            )
            ResponseEntity<ShortUrlDataOut>(response, h, HttpStatus.CREATED) // Non required
        }
        return "url acortada"; // should be url
    }
```

Let's do a first refactor

```kotlin
    fun shortener(originalUrl: String, someObject: SomeClass): String = createShortUrlUseCase.create(
            url = originalUrl,
            data = ShortUrlProperties(
                ip = someObject.attributes["ip"],
                sponsor = null
            )
        )?.let {
            val uri = someObject.redirectTo(it.hash)
            "$originalUrl,$uri" // return both, the original and the shortened
        }?: "$originalUrl," // if null, has failed, so returns the original and "" for example
```

The point here is: do `SomeClass`  is part of the API?. Somewhat `Session` will solve the "redirectTo" with a string trick, but the IP requires an extra work.

 I would like to prepare an example and share with all of you in two or three days.

**Comment by fjlopez** [comment]
This example show how to obtain such data from "session" objects:

https://github.com/UNIZAR-30246-WebEngineering/websocket-handshake-interceptor

However, it requires to subclass `TextWebSocketHandler` rather than the use of standard WebSocket annotations. Nevertheless, you can use this approach too with the WebSocket annotation that Spring provides.

**Comment by fjlopez** [comment]
If this solves your issue, close this.

**Comment by fjlopez** [comment]
@SergioBenitez755787 I think that https://github.com/UNIZAR-30246-WebEngineering/injecting-beans-websocket-serverendpoint is also relevant for you.
