### ISSUE TITLE
Websockets creando endpoint manualmente

### ISSUE THREAD

**Issue by SergioBenitez755787** [SergioBenitez755787/urlshortener#2]
Se está intentando implementar los websockets en el servidor de una forma similar a la original pero en este caso heredando de la clase EndPoint y desplegando el endpoint manualmente invocando a ServerEndpointConfig.Builder.create sin utilizar la etiqueta @ServerEndpoint ya que no conseguimos poder pasarle parámetros al constructor ni inicializando una lateinit var con @AutoWired.

Para su implementación hemos seguido los pasos indicados en la siguiente página web: 
http://expertojava.ua.es/experto/restringido/2015-16/cweb/cweb05.html#_cliente_javascript

Sin embargo, a pesar de que el proyecto compila, el cliente no es capaz de conectarse al endpoint desplegado para el websocket. No estamos seguros de si esto se debe a que el endpoint no se despliega correctamente o a que estamos cometiendo algún error en la parte del cliente, ya que en la web pone que para conectarse hay que usar la url "ws://localhost:8080/_miaplicacion_/_endpointpath_" pero no sabemos que es lo que hay que poner en _miaplicacion_.

Websockets cliente:
https://github.com/SergioBenitez755787/urlshortener/blob/benny2/app/src/main/resources/static/js/app.js

Nueva implementación de los websockets del servidor heredando de la clase EndPoint:
https://github.com/SergioBenitez755787/urlshortener/blob/benny2/delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/CsvWebSockets.kt

Despliegue del Endpoint al recibir la petición del csv:
https://github.com/SergioBenitez755787/urlshortener/blob/benny2/delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlCsvShortenerController.kt

**Comment by fjlopez** [comment]
Hola,

La llamad que hacéis en 

https://github.com/SergioBenitez755787/urlshortener/blob/aa4714ed333bb66a8a11f37dbba602224e0e8745/delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/UrlCsvShortenerController.kt#L46

no es el mecanismo "estándar" para crear el endpoint de websocket en Spring (si lo es en otros casos). Lo que se hace es crear un `@Component` y dejar que el `ServerEndpointExporter` lo registre en la ruta que aprezca en `ServerEndpoint`.

En ese caso, si `@ServerEndpoint("/test")` y el servidor se ha arrancado en el puerto 8080 la URI que debeés usar es : `ws://localhost:8080/test`. Esto se puede verificar fácilmente con Postman.

Con respecto a la inyección de dependencias, he creado una solución que ahora voy a compartir con todo el mundo que lo resuelve.

https://github.com/UNIZAR-30246-WebEngineering/injecting-beans-websocket-serverendpoint

**Comment by SergioBenitez755787** [comment]
Hola Javier,

Con la solución que propones para poder inyectar dependencias funciona todo perfectamente.

Cerramos esta issue y cuando acabemos lo de obtener la ip del cliente a partir de la sesssion de websockets cerraremos la otra issue correspondiente.

Gracias
